apiVersion: k3d.io/v1alpha2
kind: Simple
name: meucluster
servers: 1
agents: 3
ports:
  - port: "8080:30000"
    nodeFilters:
      - loadbalancer
env:
  - envVar: "http_proxy=gateway.pt.zscaler.net:80"
    nodeFilters:
      - all
  - envVar: "https_proxy=gateway.pt.zscaler.net:80"
    nodeFilters:
      - all
  - envVar: "no_proxy=.localhost,127.0.0.1,0.0.0.0,.local"
    nodeFilters:
      - all